### ISSUE TITLE
`geopy` 2.0 does not support ` vincenty

### ISSUE THREAD

**Issue by darribas** [UDST/urbanaccess#63] opened 2020-07-07 16:06 UTC
It seems that the 2.0 version of `geopy` does not support the `vincenty` distance ([link](https://github.com/geopy/geopy/blob/5362fa1a533cb003b44d4f5c51a81f2afc467ea4/docs/changelog_2xx.rst#breaking-changes)).

On a fresh install, I get:

```python
In [1]: import urbanaccess
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-ddb7d43afadf> in <module>
----> 1 import urbanaccess

/opt/conda/lib/python3.7/site-packages/urbanaccess/__init__.py in <module>
      1 from .gtfs.load import *
----> 2 from .gtfs.network import *
      3 from .gtfs.gtfsfeeds_dataframe import *
      4 from .gtfs.headways import *
      5 from .osm.load import *

/opt/conda/lib/python3.7/site-packages/urbanaccess/gtfs/network.py in <module>
      5
      6 from urbanaccess.utils import log, df_to_hdf5, hdf5_to_df
----> 7 from urbanaccess.network import ua_network
      8 from urbanaccess import config
      9 from urbanaccess.gtfs.gtfsfeeds_dataframe import gtfsfeeds_dfs

/opt/conda/lib/python3.7/site-packages/urbanaccess/network.py in <module>
      2 from sklearn.neighbors import KDTree
      3 import pandas as pd
----> 4 from geopy.distance import vincenty
      5
      6 from urbanaccess.utils import log, df_to_hdf5, hdf5_to_df

ImportError: cannot import name 'vincenty' from 'geopy.distance' (/opt/conda/lib/python3.7/site-packages/geopy/distance.py)

In [2]: import geopy

In [3]: geopy.__version__
Out[3]: '2.0.0'

In [4]:
```

Might be an easy fix to update to recommended distance?

**Comment by knaaptime** [comment] 2020-07-07 16:10
duplicate of #53 should be resolved by #62

**Closed** 2020-07-07 16:55 UTC
